# Exported from Render on 2024-11-27T13:55:15Z
databases:
  - name: Servless-pg
    plan: free
    region: frankfurt

services:
  - type: web
    name: Servless
    runtime: node
    repo: https://github.com/AlexisElef/Servless
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Servless-pg
          property: connectionString
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start