# Exported from Render on 2024-11-27T13:55:15Z
databases:
- name: Servless-pg
  databaseName: database_t33x
  user: alexis
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
  - type: web
    name: Servless
    runtime: node
    repo: https://github.com/AlexisElef/Servless
    plan: free
    envVars:
    - fromGroup: Servless
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
  version: "1"
